var GOTDB =
{
    "person":{"firstName":"birth", "lastName":"birth", "age":"birth",
        "region":"birth", "gender":"birth", "job":"yngAd", "eye color":"birth",
        "hair color":"birth", "house":"birth"},
    "nodes":{"life":["childhood", "adolescence", "young adulthood", "mid-life",
        "elder years"]},
    "ages":["child", "adolescent", "young adult", "mid-life", "elder"],
    "cities":["a large town in ", "a small village in ", "the middle of ", "",
        "that famous part of "],
    "cities2":["the large town in ", "the small village in ", "the middle of ", "",
        "this famous part of "],
    "eye colors":["blue", "brown", "green", "gray"],
    "genders":["male", "female"],
    "hair colors":["yellow", "black", "brown", "white"],
    "subjects":{"ax":["first", "second", "third"], "bx":["x", "y", "z"]},
    "clothes":{
        "[Random]":"what most young {get() social} people wear,",
        "farmer":"sun faded clothes and shoes caked in mud",
        "blacksmith":"an apron smeared black over brown clothes and thick gloves",
        "fisherman":"clothes smelling of fish and tall black boots",
        "merchant":"almost gaudy clothing of many colors",
        "rich":"adorned with fancy markings and wearing some jewelry.",
        "guard":"a leather jacket over some padded clothes",
        "commoner":"of average quality.",
        "noble":"well tailored and finely made.",
        "poor":"that doesn't fit and has all manner of rips and patches.",
        "knight":"knightly regalia. Under the tabbard displaying their coat of arms, they are wearing a fine hauberk of chainmail."},
    "solo-plots":[{
        "plot-name":"test",
        "lines":["test-lines [convnode ComplexNPC0test-node]"],
        "nodes":[{
            "name":"test-node",
            "type":"open",
            "suggestion":"aa or bb",
            "understand":[{"[ax]":["aa"]}, {"[bx]":["bb"]}],
            "rules":[{"[ax]":'show plot; say"[convnode null-node]";'},
                {"[bx]":'show plot; say"[convnode null-node]";'}]}]}],
    "multi-plots":[{"plot-name":"test", "lines":["test-first"],
        "other":{"plot-name":"test", "lines":["test-other"]}}],
    "hobbies":["wood-carving", "archery", "fishing", "horse-riding",
        "jousting", "preaching", "reading", "gardening", "making music",
        "less than legal activities", "walking", "running", "playing games",
        "building", "hawking", "sailing", "hunting", "fighting", "acting",
        "thinking", "meeting new people", "exploring", "praying", "writing",
        "socializing", "singing", "bird-watching",
        "sitting and watching the world around me."],
    "injuries":["arm missing", "leg missing", "face scar", "limp", "none"],
    "jobs":["blacksmith", "farmer", "fisherman", "guard", "knight", "merchant", "mentor"],
  //  "jobs":["guard"],
    "spouses":{"male":"wife", "female":"husband"},
    "greetings":["Good day.", "Hello.", "Hello!", "Hey!", "Hail!", "Greetings",
        "How fare thee?", "Good morrow!", "Hmm?", "What?", "", "*coughs*"],
    "greetings2":["You look well.", "You look familiar.", "Quite a day!", "",
        "I wonder how many people are here.", "What a crowd.", "What a feast.",
        "The noble family is good to us.", "What is it?",
        "You have business with me?", "I'm busy right now, what is it?",
        "You must not be from around here.", "What?", ""],
    "regions":["The Reach", "The Westerlands", "The North", "The Riverlands",
        "The Vale of Arryn", "The Stormlands", "The Crownlands",
        "The Iron Islands", // "North of the Wall",
        "Dorne"],
    "regionLines":{
        "The Reach":"The Reach is aptly named. We're the ones who give your hand something to do at the table. As the most fertile region of the Seven Kingdoms, we grow the lion's share of the grains and fruit that feed this country.",
        "The Westerlands":"Fools look at the Westerlands and see gold. Fools see our wealth and call it strength. Gold is just another rock. The Westerlands are strong because of House Lannister. From strong leadership comes unity; from unity comes power.",
        "The North":"The North is larger than the other six kingdoms combined.",
        "The Riverlands":"The Riverlands is our home and Gods help us we love it.",
        "The Vale of Arryn":"The borders of the Vale are held to be the Bite to the north, the Bay of Crabs to the south, the Mountains of the Moon to the west and the Narrow Sea to the east.",
        "The Stormlands":"The Stormlands is one of the nine constituent regions of the Seven Kingdoms. It is located on the south east coast of the continent of Westeros, on the shores of the Narrow Sea, south of the Crownlands and north of Dorne. The Stormlands are ruled from the castle of Storm's End by House Baratheon.",
        "The Crownlands":"The Crownlands are located on the east coast of Westeros, on the shores of the Narrow Sea, north of the Stormlands and south of the Vale of Arryn.",
        "The Iron Islands":"Where the North has its honor and the South its chivalry, the Iron Islands has its strength.",
        // "North of the Wall":"We're not in the Seven Kingdoms. I am of the
        // free folk from the real north",
        "Dorne":"Dorne is in the south of Westeros and has maintained many of it's customs by being the last region to join the Seven Kingdoms. And joined by marriage politics not conquest like the rest."},
    "classes":["poor", "commoner", "rich", "noble"],
    "houses":{
        "North of the Wall":[],
        "The Crownlands":[
            {
                "name":"Baratheon of King's Landing",
                "rank":"royal",
                "sigil":"the crowned stag of Baratheon black on gold and the lion of Lannister golden on red combatant"},
            {
                "name":"Blount",
                "rank":"noble",
                "sigil":"vert, A red bend sinister gules between two black porcupines on green"},
            {
                "name":"Brune",
                "rank":"noble",
                "sigil":"argent, a bear's paw erased within a double tressure tenné"},
            {
                "name":"Gaunt",
                "rank":"noble",
                "sigil":"three black lances upright on pink, between black flaunches"},
            {"name":"Rosby", "rank":"noble",
                "sigil":"three red chevronels on ermine"},
            {
                "name":"Rykker",
                "rank":"noble",
                "sigil":"two black warhammers crossed on a white saltire on blue"},
            {"name":"Slynt", "rank":"noble",
                "sigill":"sable, a bloody spear, tipped gules"},
            {"name":"Stokeworth", "rank":"noble",
                "sigil":"vert, a lamb couchant argent holding a goblet"},
            {"name":"Thorne", "rank":"noble",
                "sigil":"a silver flail on red within a black border"}],
        "The North":[
            {"name":"Stark", "rank":"great",
                "sigil":"a running grey direwolf, on an ice-white field"},
            {"name":"Cerwyn", "rank":"noble",
                "sigil":"argent, a battle-axe paleways sable"},
            {
                "name":"Dustin",
                "rank":"noble",
                "sigil":"two longaxes crossed, a black crown between their heads on a field of yellow"},
            {"name":"Hornwood", "rank":"noble",
                "sigil":"a brown bull moose on an orange field."},
            {"name":"Karstark", "rank":"noble",
                "sigil":"a white sunburst on black"},
            {
                "name":"Manderly",
                "rank":"noble",
                "sigil":"a white merman with green hair, over a blue-green field"},
            {"name":"Mormont", "rank":"noble",
                "sigil":"a wood vert, a bear sable"},
            {
                "name":"Ryswell",
                "rank":"noble",
                "sigil":"bronze, a horse's head sable orbed and maned gules within a bordure engrailed sable"},
            {"name":"Umber", "rank":"noble",
                "sigil":"four gold chains linked by a central ring on dark red"}],
        "The Riverlands":[
            {
                "name":"Frey",
                "rank":"great",
                "sigil":"the two stone grey towers and bridge of the Twins, on a dark grey field, surmounting an escutcheon of blue water."},
            {
                "name":"Blackwood",
                "rank":"noble",
                "sigil":"a flock of black ravens surmounting a dead white weirwood tree"},
            {
                "name":"Bracken",
                "rank":"noble",
                "sigil":"a red stallion on a gold field, over a brown escutcheon"},
            {"name":"Mallister", "rank":"noble",
                "sigil":"a silver eagle on a blue field"},
            {"name":"Mooton", "rank":"noble",
                "sigil":"a red salmon on a white fiel"},
            {"name":"Smallwood", "rank":"noble",
                "sigil":"or, six acorns tenné, three, two and one"}],
        "The Westerlands":[
            {"name":"Lannister", "rank":"great",
                "sigil":"a golden lion rampant on a crimson field."},
            {"name":"Crakehall", "rank":"noble",
                "sigil":"a black and white brindled boar on brown"},
            {"name":"Lannister of Lannisport", "rank":"noble", "sigil":""},
            {"name":"Lefford", "rank":"noble",
                "sigil":"a golden pile on sky blue, a sun right in the sky"},
            {"name":"Marbrand", "rank":"noble",
                "sigil":"a burning tree, orange on smoke"},
            {
                "name":"Payne",
                "rank":"noble",
                "sigil":"purple and white chequy with gold coins in the checks."},
            {"name":"Sarsfield", "rank":"noble",
                "sigil":"a green arrow on a white bend on green"},
            {"name":"Serrett", "rank":"noble",
                "sigil":"argent, a peacock in his pride proper"},
            {"name":"Westerling", "rank":"noble",
                "sigil":"six white shells on a sand-colored field"},
            {
                "name":"Yarwyck",
                "rank":"noble",
                "sigil":"argent, two halberds saltireways tenny hafted sable between four lozenges of the second"}],
        "The Reach":[
            {"name":"Tyrell", "rank":"great", "sigil":"a golden rose on green"},
            {
                "name":"Ashford:",
                "rank":"noble",
                "sigil":"tenny, a sun in splendour beneath a chevron inverted argent"},
            {
                "name":"Beesbury",
                "rank":"noble",
                "sigil":"paly or and sable, on a pale of the last three beehives of the first"},
            {"name":"Bulwer", "rank":"noble",
                "sigil":"aanguine, a bull`s skull argent"},
            {"name":"Cuy", "rank":"noble", "sigil":"six yellow flowers on blue"},
            {
                "name":"Florent",
                "rank":"noble",
                "sigil":"ermine, a fox's head cabossed within an annulet of flowers, all proper"},
            {"name":"Fossoway", "rank":"noble", "sigil":"a red apple on gold"},
            {"name":"Hightower", "rank":"noble",
                "sigil":"cendrée, a tower argent with a beacon on fire gules"},
            {"name":"Leygood", "rank":"noble",
                "sigil":"tenny, three thunderbolts in fess sable"},
            {"name":"Oakheart", "rank":"noble",
                "sigil":"three oak leaves on gold"},
            {"name":"Redwyne", "rank":"noble",
                "sigil":"azure, a grape cluster proper"},
            {"name":"Tarly", "rank":"noble",
                "sigil":"a huntsman in redon a green field"}],
        "The Stormlands":[
            {"name":"Baratheon", "rank":"great",
                "sigil":"a crowned black stag on gold"},
            {"name":"Errol", "rank":"noble", "sigil":"A haystack"},
            {"name":"Estermont", "rank":"noble",
                "sigil":"a green seaturtle in green"},
            {"name":"Grandison", "rank":"noble",
                "sigil":"a sleeping black great cat"},
            {
                "name":"Musgood",
                "rank":"noble",
                "sigil":"quarterly: A golden pavillion on blue, a green laurel crown on white"},
            {"name":"Peasebury", "rank":"noble",
                "sigil":"argent, a pea pod open within a bordure of peas vert"},
            {
                "name":"Tarth",
                "rank":"noble",
                "sigil":"gules, a sun in splendour Or quartered with azure, an increscent argent"},
            {"name":"Trant", "rank":"noble",
                "sigil":"the silhouette of a hanged man in the night"},
            {"name":"Wylde", "rank":"noble", "sigil":"a maelstrom aquamarine"}],
        "The Vale of Arryn":[
            {
                "name":"Arryn",
                "rank":"great",
                "sigil":"a white falcon volant and crescent moon on a blue field."},
            {"name":"Corbray", "rank":"noble",
                "sigil":"argent, a raven volant sable holding a heart gule"},
            {
                "name":"Egen",
                "rank":"noble",
                "sigil":"argent, on a chief azure an increscent of the first between a sun in splendour gold and a star of the first"},
            {"name":"Lynderly", "rank":"noble",
                "sigil":"eleven green snakes on a black field"},
            {"name":"Hunter", "rank":"noble",
                "sigil":"tenny, five arrows in fret with heads to chief argent"},
            {
                "name":"Moore",
                "rank":"noble",
                "sigil":"argent, three spearheads bronze prome within a bordure embattled of the same"},
            {"name":"Royce", "rank":"noble",
                "sigil":"tenny pelletty, an orle of runes sable"},
            {"name":"Tollett", "rank":"noble", "sigil":"pily, grey and black"},
            {"name":"Waynwood", "rank":"noble",
                "sigil":"a black broken wheel on green"}],
        "Dorne":[
            {"name":"Martell", "rank":"great",
                "sigil":"a red sun pierced by a gold spear, on an orange field"},
            {
                "name":"Blackmont",
                "rank":"noble",
                "sigil":"a flying grey and white vulture, grasping a baby in its talons, on a black field"},
            {"name":"Dayne", "rank":"noble",
                "sigil":"a sword and a falling star on a lavender background"},
            {"name":"Jordayne", "rank":"noble",
                "sigil":"chequy light and dark green, a gold quill"},
            {"name":"Manwoody", "rank":"noble",
                "sigil":"a crowned skull on black"},
            {"name":"Qorgyle", "rank":"noble",
                "sigil":"three black scorpions on red"},
            {"name":"Uller", "rank":"noble",
                "sigil":"a rayonne yellow over crimson"},
            {"name":"Allyrion", "rank":"noble",
                "sigil":"gyronny gules and sable, a gold hand"},
            {"name":"Yronwood", "rank":"noble",
                "sigil":"a black portcullis grill over sand"}],
        "The Iron Islands":[
            {"name":"Greyjoy", "rank":"great",
                "sigil":"a golden kraken on a black field"},
            {"name":"Blacktyde", "rank":"noble",
                "sigil":"vairy green and black"},
            {"name":"Botley", "rank":"noble",
                "sigil":"a shoal of silver fish on pale green"},
            {"name":"Goodbrother", "rank":"noble",
                "sigil":"a gilded black horn on red"},
            {"name":"Harlaw", "rank":"noble", "sigil":"silver scythe on black"},
            {
                "name":"Kenning of Kayce",
                "rank":"noble",
                "sigil":"quarterly tenny and sable, four suns in splendour counterchanged"},
            {"name":"Merlyn", "rank":"noble",
                "sigil":"argent, twining waterspouts vert"},
            {"name":"Sparr", "rank":"noble", "sigil":"an oak saltire on blue"}]},
    "moods":["angry", "calm", "tired", "happy", "sad", "excited", "nervous",
        "nervous", "hungry", "thristy", "fine", "good", "well"],
    "physicalTraits":["large", "tall", "sick", "dirty",
        "well-dressed", "agile", "musclar", "beautiful"],
    "mentalTraits":["perceptive", "creative", "intelligent", "organized",
        "diligent", "reliable", "energetic", "assertive", "popular", "gentle",
        "trusting", "generous", "content", "emotional", "brave"],
    "childEvents":[
        {"event":"Cool Older Brother",
            "line":"I wished to be just like my older brother."},
        {
            "event":"Mean Older Brother",
            "line":"My older brother scared me growing up and then the woman he married."},
        {"event":"Cool Younger Brother",
            "line":"I wrestled my younger brother and let him win sometimes."},
        {"event":"Mean Younger Brother",
            "line":"My litle brother would hit me for no reason."},
        {
            "event":"Cool Older Sister",
            "line":"It was too bad that my big sister moved away to live with her husband. We don't see each other much."},
        {
            "event":"Mean Older Sister",
            "line":"I was happy when my older sister was married to some man so I didn't have to see her so much."},
        {
            "event":"Cool Younger Sister",
            "line":"I loved growing up with my little sister. She and I would laugh and play outside all the time"},
        {
            "event":"Mean Younger Sister",
            "line":"My little sister was a brat who always fake cried to get what she wanted."},
        {
            "event":"Parent Death",
            "effect":{"emotional":"+35"},
            "line":"One of my parent's died when I was young and it left a big mark on my life.",
            "requires":{"childTone":{"is":"Negative"}}},
        {"event":"Injury", "effect":{"brave":"-35", "assertive":"-25"},
            "line":"I was injured while playing outside",
            "requires":{"childTone":{"is":"Negative"}}},
        {
            "event":"War Child",
            "effect":{"brave":"+25", "gentle":"-25", "trusting":"-50",
                "perceptive":"+10", "creative":"+10"},
            "line":"Terrible battles happened all the time while I was growing up. I have many nightmares about it.",
            "requires":{"childTone":{"is":"Negative"}}},
        {"event":"Family Farm", "effect":{"diligent":"+20"},
            "line":"I worked on my family farm from a young age",
            "requires":{"social":{"not":["royal", "noble"]}}},
        {
            "event":"Abuse",
            "effect":{"gentle":"-45", "trusting":"-70", "perceptive":"+10",
                "creative":"-10"},
            "line":"I rather not talk about everything from my childhood.",
            "requires":{"childTone":{"is":"Negative"}}},
        {"event":"accident", "effect":{"muscular":"-35"},
            "line":"I had a pretty bad accident",
            "requires":{"childTone":{"is":"Negative"}}},
        {"event":"Kind Family", "line":"I had a kind family.",
            "requires":{"childTone":{"is":"Positive"}}},
        {"event":"Mean Family", "line":"I had a mean family.",
            "effect":{"trusting":"-75"},
            "requires":{"childTone":{"is":"Negative"}}},
        {"event":"Average Family",
            "line":"I'd say my family was pretty typical."},
        {"event":"Rich Family", "line":"We were very well off.",
            "requires":{"social":{"not":["poor", "Slave"]}}}, ],
    "adoleEvents":[
        {"event":"Apperentice", "effect":{"inteligent":"+20"},
            "line":"I became an apprentice in the service of a carpenter.",
            "requires":{"social":{"not":["royal", "noble"]}}},
        {"event":"Family Farm", "effect":{"diligent":"+20"},
            "line":"I worked on my family farm growing up",
            "requires":{"social":{"not":["royal", "noble"]}}},
        {"event":"Cabin Boy", "effect":{"diligent":"+20"},
            "line":"I traveled between Oldtown and Volantis as a cabin boy.",
            "requires":{"social":{"not":["royal", "noble"]}}},
        {"event":"Squire", "effect":{"diligent":"+20"},
            "line":"A knight requested I be his squire",
            "requires":{"social":{"is":["noble"]}}},
        {"event":"Fun Adventure",
            "line":"A couple of friends and I went on a fun adventure.",
            "requires":{"adoleTone":{"is":"Positive"}}},
        {
            "event":"Dangerous Adventure",
            "line":"A couple of friends and I went on a dangerous adventure. We almost died.",
            "requires":{"adoleTone":{"is":"Negative"}}},
        {
            "event":"Own Dangerous Illness",
            "line":"I got really sick one time. I had a high fever for a week. My family wasn't sure I'd make it."},
        {
            "event":"Bro Dangerous Illness",
            "line":"My brother a cold that lasted for months. We went to several doctors who were not sure what it was."},
        {
            "event":"Sis Dangerous Illness",
            "line":"My brother stepped on something that turned his foot green. Before they cut it off, it got better luckily."},
        {"event":"Pet cat", "line":"I had a pet cat growing up."},
        {"event":"Pet dog nice", "line":"My dog was really sweet to everyone."},
        {"event":"Pet dog mean",
            "line":"I also had a hound that bit a few neighbours in his time."},
        {"event":"Pet bird", "line":"I made friends with a crow."},
        {"event":"Changed Ownership",
            "line":"My owner lost a bet and I changed ownership.",
            "requires":{"social":{"is":"Slave"}}},
        {"event":"Avg Adole", "line":"I did lots of chores around the house."},
        {"event":"Traveled often", "line":"My family moved a few times.",
            "requires":{"social":{"not":["poor"]}}},
        {"event":"Early Marriage", "line":"I married earlier than most.",
            "requires":{"marriage":{"is":"$none"}},
            "effect":{"marriage":"$married"}}],
    "yngAdEvents":[
        {"event":"traveled Riverlands",
            "line":"I traveled around the Riverlands",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Iron Island",
            "line":"I traveled around the Iron Islands",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Riverlands",
            "line":"I traveled around the Crownlands",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Riverlands", "line":"I traveled around the North",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Riverlands", "line":"I traveled around Dorne",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Riverlands", "line":"I traveled around The Vale",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Braavos", "line":"I traveled to Braavos once",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Riverlands",
            "line":"I traveled around the Stormlands",
            "requires":{"social":{"not":"poor"}}},
        {"event":"traveled Riverlands", "line":"I traveled around the Reach",
            "requires":{"social":{"not":"poor"}}},
        {"event":"War", "line":"I joined the war effort. It was rough.",
            "selectWeight":1, "corr":{"events":{"adoleEvent":{"Squire":"1"}}}},
        {"event":"Imprisoned",
            "line":"I was in jail. I don't need to tell you about it."},
        {
            "event":"Imprisoned",
            "line":"I stole something one time. I was in jail and learned my lesson"},
        {"event":"Work injury",
            "line":"I was injured on the job. But it wasn't too bad.",
            "requires":{"yngAdTone":{"is":"Negative"}}},
        {"event":"Enjoy work", "line":"I didn't mind working.",
            "effect":{"diligent":"+20"},
            "requires":{"yngAdTone":{"is":"Positive"}}},
        {"event":"Hate Work", "line":"I hated working.",
            "effect":{"diligent":"-40"},
            "requires":{"yngAdTone":{"is":"Negative"}}},
        {"event":"Bored", "line":"I don't remember doing much interesting."},
        {"event":"Struggled to eat", "line":"Finding food was a struggle",
            "requires":{"social":{"not":["rich", "noble", "royal"]}},
            "yngAdTone":{"is":"Negative"}},
        {"event":"Changed Ownership",
            "line":"I was given to another master to resolve a debt.",
            "requires":{"social":{"is":"Slave"}}},
        {"event":"Young Blacksmith", "line":"I was trained to be a blacksmith",
            "requires":{"job":{"is":["[Random]"]}},
            "effect":{"job":"$blacksmith"}},
        {"event":"Young Guard", "line":"I was trained to be a town guard",
            "requires":{"job":{"is":["[Random]"]}}, "effect":{"job":"$guard"}},
        {"event":"Young Fisherman",
            "line":"I went fishing and was able to make some money.",
            "requires":{"job":{"is":["[Random]"]}},
            "effect":{"job":"$fisherman"}},
        {"event":"Set Free", "line":"I finally gained my freedom.",
            "requires":{"social":{"is":"Slave"}}, "effect":{"social":"$poor"}},
        {
            "event":"Young Guard",
            "line":"Someone told be I should join the local guards. It worked out.",
            "requires":{"job":{"is":["[Random]"]}, "muscular":{"above":"50"}},
            "effect":{"job":"guard"}},
        {
            "event":"Good Marriage",
            "line":"I married the love of my life.",
            "requires":{"marriage":{"is":"none"}, "yngAdTone":{"is":"Positive"}},
            "effect":{"marriage":"$married"}},
        {
            "event":"Bad Marriage",
            "line":"I didn't realize what I was getting into with my marriage.",
            "requires":{"marriage":{"is":"none"}, "yngAdTone":{"is":"Negative"}},
            "effect":{"marriage":"$married"}},
        {
            "event":"Neutral Marriage",
            "line":"My marriage has been alright I guess.",
            "requires":{"marriage":{"is":"none"},
                "effect":{"marriage":"$married"}},
            "effect":{"marriage":"$married"}},
        {
            "event":"Spouse death",
            "line":"My wife died in childbirth.",
            "requires":{"gender":"male", "marriage":"married",
                "midAdTone":{"is":"Negative"}}, "effect":{"marriage":"$none"}},
        {"event":"Forced Marriage", "line":"I had an arranged marriage",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"Win tourney",
            "line":"I won a prize in a local fighting tourney",
            "requires":{"job":"knight"}},
        {"event":"inheritance", "line":"I received a large inheritance",
            "requires":{"yngAdTone":{"is":"Positive"}},
            "effect":{"social":"rich"}},
        {
            "event":"Young Knight",
            "line":"I was knighted.",
            "requires":{
                "job":{"is":["[Random]"],
                    "social":{"is":["rich", "noble", "royal"]}},
                "muscular":{"above":"50"}}, "effect":{"job":"$knight"}},
        {"event":"Assault",
            "line":"One night I was assaulted but fought off the attackers.",
            "requires":{"yngAdTone":{"is":"Negative"}}},
        {
            "event":"Young Merchant",
            "line":"I started making a living by trading goods. I started small but kept expanding.",
            "requires":{"job":{"is":["[Random]"]}},
            "effect":{"job":"$merchant"}}],
    "midAdEvents":[
        {"event":"Draft",
            "line":"I was drafted to fight in the war for a time."},
        {"event":"work injury", "line":"I dropped a large object on my foot.",
            "requires":{"midAdTone":{"is":"Negative"}}},
        {"event":"Imprisoned",
            "line":"I was framed for a crime and ended up in jail.",
            "requires":{"midAdTone":{"is":"Negative"}}},
        {
            "event":"Assault",
            "requires":{"midAdTone":{"is":"Negative"}},
            "line":"While travelling between towns I was mugged by some criminal scum."},
        {"event":"lost land",
            "line":"My property was taken from me and I was homeless.",
            "effect":{"social":"$poor"}},
        {"event":"Good Marriage", "line":"I married the love of my life.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"financial success",
            "requires":{"midAdTone":{"is":"Positive"}},
            "line":"I prospered at my career and made some good contacts.",
            "requires":{"not":"Slave"}, "effect":{"social":"rich"}},
        {"event":"financial ruin",
            "line":"I had miserable luck in my career and lost a lot.",
            "requires":{"not":"Slave"}, "effect":{"social":"poor"}},
        {"event":"parent death",
            "line":"One of my parents passed away due to illness."},
        {"event":"spouse death", "line":"My wife died in childbirth.",
            "requires":{"gender":"male", "marriage":{"is":"married"}},
            "effect":{"marriage":"none"}},
        {
            "event":"Bad Marriage",
            "requires":{"midAdTone":{"is":"Negative"}},
            "line":"I didn't realize what I was getting into with my marriage.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"Neutral Marriage",
            "line":"My marriage has been alright I guess.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"Forced Marriage", "line":"I had an arranged marriage.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"Enjoy work", "line":"Having a job isn't half bad.",
            "requires":{"midAdTone":{"is":"Positive"}}},
        {"event":"Hate Work", "line":"I don't like my job.",
            "requires":{"midAdTone":{"is":"Negative"}}},
        {"event":"Bored", "line":"It seems like I'm often bored of my routine."},
        {
            "event":"Struggled to afford food",
            "line":"My job doesn't pay very well and it's sometimes hard to get food.",
            "requires":{"social":{"not":["rich", "noble", "royal", "Slave"]}},
            "midAdTone":{"is":"Negative"}},
        {"event":"Set Free", "line":"I finally gained my freedom.",
            "requires":{"social":{"is":"Slave"}},
            "requires":{"midAdTone":{"is":"Positive"}},
            "effect":{"social":"$poor"}},
        {"event":"Changed Ownership",
            "line":"After I tried to run away, I was given on to a new owner.",
            "requires":{"social":{"is":"Slave"}}}],
    "elderEvents":[
        {"event":"Assault", "requires":{"elderTone":{"is":"Negative"}},
            "line":"I was robbed on the street. Who beats old people?"},
        {"event":"Good Marriage", "requires":{"elderTone":{"is":"Positive"}},
            "line":"I married the love of my life.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"spouse death",
            "line":"My spouse died after becoming very sick.",
            "requires":{"marriage":{"is":"married"}},
            "effect":{"marriage":"$none"}},
        {
            "event":"Bad Marriage",
            "line":"I didn't realize what I was getting into with my marriage.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"Neutral Marriage",
            "line":"My marriage has been alright I guess.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"Late Marriage", "line":"I finally got married recently.",
            "requires":{"marriage":{"is":"none"}},
            "effect":{"marriage":"$married"}},
        {"event":"Enjoy work",
            "line":"I still work, I like having something to do.",
            "requires":{"midAdTone":{"is":"Positive"}}},
        {"event":"Hate Work",
            "line":"I wish I could retire, but I have to work.",
            "requires":{"midAdTone":{"is":"Negative"}}},
        {"event":"Bored", "line":"I don't have much to do these days."},
        {"event":"Struggled to afford food",
            "line":"At my age it's hard to get by without support.",
            "requires":{"social":{"not":["rich", "noble", "royal"]}},
            "midAdTone":{"is":"Negative"}},
        {"event":"Changed Ownership",
            "line":"They don't really think I am very useful these days.",
            "requires":{"social":{"is":"Slave"}}},
        {"event":"Financial success",
            "line":"I prospered at my career and made some good contacts.",
            "requires":{"not":"slave"}, "effect":{"social":"rich"}},
        {"event":"Financial ruin",
            "line":"I had miserable luck in my career and lost a lot.",
            "requires":{"not":"slave"}, "effect":{"social":"poor"}},
        {"event":"Set Free", "line":"I finally gained my freedom.",
            "requires":{"social":{"is":"Slave"}}, "effect":{"social":"$poor"}},
        {
            "event":"Community Leader",
            "line":"I became important in my town leadership and many come to me for advise."},
        {"event":"Respected",
            "line":"I live a quiet life and am well respected."}],
    "gender":["male", "female"],
    "names":{
        "female":["Aalya", "Abagal", "Abrey", "Arby", "Addysen", "Edeline",
            "Adrya", "Adryana", "Adrielle", "Ayleen", "Aymee", "Alisha",
            "Ariyana", "Alarina", "Alara", "Alenis", "Alerah", "Anera",
            "Alessa", "Alexes", "Alira", "Arice", "Anicia", "Aline", "Alise",
            "Ellisha", "Elison", "Alissa", "Alia", "Aliza", "Arlis", "Almia",
            "Alora", "Alysia", "Alis", "Alaysha", "Alson", "Alssa", "Amarda",
            "Amyra", "Ambre", "Amelira", "Arina", "Eyme", "Aimya", "Arah",
            "Anabes", "Anari", "Anaris", "Anysa", "Anrea", "Arika", "Aniza",
            "Aniga", "Annarel", "Annalys", "Annyte", "Annila", "Ensley",
            "Anya", "Arecel", "Arrely", "Aryana", "Aranna", "Arenna", "Arrei",
            "Arlenna", "Ashlei", "Ashlanna", "Ashlyh", "Astris", "Aobrey",
            "Aurola", "Avya", "Avelley", "Ayara", "Ayenna", "Eyla", "Baylee",
            "Barbenna", "Beylee", "Bellin", "Bernyce", "Bethally", "Bancey",
            "Brandis", "Brealla", "Breannei", "Breyna", "Breniell", "Breonna",
            "Brigot", "Brianel", "Brinna", "Brannelle", "Bredgit", "Bienne",
            "Brienna", "Brise", "Bryeana", "Brynna", "Briyenn", "Catryn",
            "Catlyn", "Cemrin", "Camyla", "Camylle", "Carynne", "Caryss",
            "Carlys", "Carmin", "Carlys", "Catlina", "Cathelyne", "Cayra",
            "Celia", "Cercilia", "Celesse", "Ceria", "Cerlina", "Charlyse",
            "Chyanne", "Chyenne", "Chlowee", "Chrysha", "Christys", "Cliara",
            "Cliera", "Claere", "Clara", "Clare", "Clarysse", "Cladin", "Cira",
            "Dainis", "Dania", "Darna", "Dannya", "Darlyne", "Dasina",
            "Dayana", "Deranna", "Delylah", "Dyana", "Dyanne", "Dyanna",
            "Donnis", "Dorthy", "Elen", "Enith", "Elayna", "Elayne", "Eleana",
            "Eleanah", "Ellena", "Elyana", "Elyse", "Elize", "Ellya", "Elrie",
            "Elna", "Emely", "Emilee", "Emilya", "Emmelyne", "Esthis", "Eyva",
            "Evelyne", "Fiyona", "Fryda", "Gabielle", "Gabrelle", "Giya",
            "Gianas", "Giannis", "Gillis", "Giyana", "Glorina", "Grayce",
            "Graycie", "Gwendys", "Heyley", "Heiley", "Haleigh", "Hayana",
            "Heighden", "Haylise", "Helenys", "Helna", "Ilyana", "Ireyne",
            "Airis", "Aiana", "Aianna", "Jacline", "Jaida", "Jaide", "Jaidyn",
            "Jaelyn", "Jaeda", "Jaedyn", "Jaena", "Jaeneth", "Jaslin",
            "Jasline", "Jeyna", "Jeyla", "Jesmyn", "Jaenis", "Jenifire",
            "Jaennis", "Jilliyan", "Jocey", "Joenne", "Josey", "Jorlyn",
            "Jadith", "Julina", "Julienna", "Juline", "Jelissa", "Kaysie",
            "Kaenna", "Kaelys", "Kaina", "Khailee", "Kaylee", "Kailyn",
            "Kaithlyn", "Khailey", "Kiara", "Kiren", "Kari", "Katherin",
            "Kathlyn", "Kathryn", "Katlyn", "Katryna", "Keila", "Keira",
            "Kailsey", "Kendris", "Kianne", "Keynna", "Kenyse", "Khelsie",
            "Kaela", "Kiyana", "Kiyara", "Klissa", "Krestenne", "Kristyne",
            "Kyra", "Kina", "Kylis", "Kyra", "Laycie", "Laina", "Lannia",
            "Laerra", "Laryss", "Laurane", "Lauris", "Lauryn", "Lyla", "Lehna",
            "Laenah", "Leyanna", "Lenila", "Lelani", "Laena", "Lexia",
            "Lexise", "Lina", "Liyana", "Liya", "Lylian", "Liliyana",
            "Lilliyan", "Linly", "Laina", "Lenda", "Lendsey", "Laisa",
            "Laoren", "Lorenah", "Lusia", "Luciya", "Lyndia", "Maycey",
            "Maecy", "Maedalyn", "Maralynn", "Maddeson", "Madeleine",
            "Madilyn", "Madysen", "Maygen", "Maianae", "Melleah", "Maliya",
            "Maellery", "Mansy", "Marya", "Mariya", "Marinah", "Mariyam",
            "Maryana", "Mariyanna", "Marybel", "Mariela", "Marielyn", "Malina",
            "Marilla", "Marleigh", "Marleina", "Marleya", "Mertha", "Mariyam",
            "Meya", "Mayra", "Mearow", "Melarie", "Melahnie", "Mellinna",
            "Melinsa", "Meralith", "Myna", "Milah", "Minella", "Miana",
            "Miranna", "Mereya", "Melian", "Meya", "Monira", "Mysa", "Nalia",
            "Natari", "Nathaleya", "Nira", "Neina", "Nera", "Nyla", "Nysah",
            "Nyra", "Olira", "Palina", "Rana", "Riyana", "Ranel", "Raina",
            "Reyanna", "Relina", "Reila", "Reina", "Renei", "Rila", "Rina",
            "Rosyn", "Railey", "Saede", "Salna", "Samaya", "Sanda", "Sarsah",
            "Sarisa", "Sesa", "Sava", "Sanah", "Selsa", "Selira", "Sanira",
            "Shennen", "Sheran", "Shana", "Shela", "Sharley", "Sofina",
            "Soniya", "Sanya", "Sophey", "Staicey", "Stelsa", "Sosan",
            "Suesane", "Sylvina", "Taliya", "Taniya", "Talana", "Taria",
            "Tanea", "Tarla", "Taryne", "Teya", "Tayla", "Teressa", "Tesha",
            "Thalina", "Tila", "Tiyana", "Tiffally", "Teena", "Tacy", "Trysta",
            "Valeris", "Vanesha", "Valian", "Vevienne"],
        "male":["Abelar", "Addam", "Addison", "Aegon", "Aegor", "Aemon",
            "Aenar", "Aenys", "Aeron", "Aerys", "Aethan", "Aethelmure",
            "Aggar", "Aggo", "Agrivane", "Aladale", "Albar", "Albett",
            "Alebelly", "Alequo", "Alesander", "Alester", "Alfyn", "Allar",
            "Allard", "Alleras", "Alliser", "Alvyn", "Alyce", "Alyn", "Amabel",
            "Ambrode", "Ambrose", "Amerei", "Amory", "Andar", "Anders",
            "Andrew", "Andrey", "Andrik", "Andros", "Androw", "Anguy",
            "Antario", "Anvil", "Ardrian", "Areo", "Argilac", "Argrave",
            "Arlan", "Armen", "Armond", "Arneld", "Arnell", "Arnolf", "Aron",
            "Arrec", "Arron", "Arryk", "Arson", "Arthur", "Artos", "Artys",
            "Arwood", "Arwyn", "Arys", "Assadora", "Aubrey", "Aurane", "Axell",
            "Bael", "Baelor", "Ballabar", "Balman", "Balon", "Bandy", "Bannen",
            "Barristan", "Barth", "Bass", "Bayard", "Beardless", "Beck",
            "Bedwyck", "Belgrave", "Bellegere", "Belwas", "Ben", "Benedar",
            "Benedict", "Benfred", "Benfrey", "Benjen", "Bennard", "Bennarion",
            "Bennet", "Bennis", "Beren", "Beric", "Bernarr", "Beron",
            "Bertram", "Betharios", "Big", "Biter", "Black", "Blane",
            "Bluetooth", "Bodger", "Bonifer", "Borcas", "Boremund", "Boros",
            "Bors", "Bowen", "Bradamar", "Bran", "Brandon", "Branston",
            "Brenett", "Bronn", "Brusco", "Bryan", "Bryce", "Bryen", "Brynden",
            "Buford", "Burton", "Butterbumps", "Byam", "Byan", "Byren",
            "Byron", "Cadwyl", "Cadwyn", "Caleotte", "Calon", "Carrot",
            "Castos", "Cayn", "Cedric", "Cedrik", "Cellador", "Cerrick",
            "Cetheres", "Chayle", "Chett", "Chiggen", "Chiswyck", "Clarence",
            "Clayton", "Clement", "Cleon", "Cleos", "Cletus", "Cley",
            "Cleyton", "Clifford", "Clydas", "Cohollo", "Coldhands", "Colemon",
            "Colen", "Colin", "Collio", "Colloquo", "Colmar", "Conn", "cont",
            "Conwy", "Corliss", "Cortnay", "Cosgrove", "Cotter", "Courtenay",
            "Cragorn", "Craster", "Crawn", "Cregan", "Creighton", "Cressen",
            "Creylen", "Criston", "Cuger", "Cutjack", "Daario", "Dacks",
            "Daemon", "Daeron", "Dafyn", "Dagmer", "Dagon", "Dagos", "Dake",
            "Dale", "Damion", "Damon", "Dan", "Dancy", "Danny", "Danwell",
            "Dareon", "Daryn", "Daven", "Davos", "Del", "Delonne", "Delp",
            "Demon", "Denestan", "Dennett", "Dennis", "Denyo", "Denys",
            "Deremond", "Dermot", "Desmond", "Devan", "Deziel", "Dick",
            "Dickon", "Dilly", "Dirk", "Dobber", "Dolf", "Domeric", "Donal",
            "Donel", "Donella", "Donnel", "Donnis", "Donnor", "Doran",
            "Dormund", "Dorren", "Drennan", "Dryn", "Dudley", "Dunaver",
            "Dunk", "Dunsen", "Dunstan", "Duram", "Durran", "Dyah", "Dykk",
            "Ebrose", "Eddard", "Edderion", "Eddison", "Eden", "Edgerran",
            "Edmund", "Edmure", "Edmyn", "Edric", "Edrick", "Edwyd", "Edwyle",
            "Edwyn", "Eggon", "Elbert", "Eldiss", "Eldon", "Eldred", "Ellery",
            "Elmar", "Elwood", "Elyas", "Elyn", "Elys", "Emmon", "Emmond",
            "Emrick", "Endehar", "Endrew", "Enger", "Eon", "Erik", "Eroeh",
            "Erreck", "Erreg", "Erren", "Errok", "Erryk", "Esgred", "Ethan",
            "Euron", "Eustace", "Eyron", "Farlen", "Ferrego", "Ferret",
            "Flement", "Fogo", "Forley", "Fralegg", "Franklyn", "Frenken",
            "Gage", "Galbart", "Galladon", "Gallard", "Galtry", "Gareth",
            "Garin", "Gariss", "Garizon", "Garlan", "Garrett", "Garrison",
            "Garse", "Garth", "Gascoyne", "Gawen", "Gelmarr", "Gendel",
            "Gendry", "Gerald", "Gerardys", "Geremy", "Gergen", "Gerion",
            "Germund", "Gerold", "Gerren", "Gevin", "Ghael", "Ghost",
            "Gilbert", "Gillam", "Gilwood", "Gladden", "Glendon", "Godric",
            "Godry", "Godwyn", "Goodwin", "Gorghan", "Gormon", "Gormond",
            "Gorne", "Gorold", "Gowen", "Gran", "Grance", "Grazdan",
            "Greatheart", "Greenbeard", "Gregor", "Grenn", "Grey", "Greydon",
            "Griffin", "Grigg", "Groleo", "Grubbs", "Gueren", "Gulian",
            "Gunthor", "Guthor", "Guyard", "Guyne", "Gwayne", "Gylbert",
            "Gyles", "Gynir", "Haegon", "Haereg", "Haggo", "Hake", "Hal",
            "Halder", "Halleck", "Hallis", "Halmon", "Halys", "Harbert",
            "Hareth", "Harlan", "Harlen", "Harlon", "Harmen", "Harmond",
            "Harmund", "Harmune", "Harodon", "Harrag", "Harras", "Harren",
            "Harrion", "Harrold", "Harry", "Harsley", "Harwin", "Harwood",
            "Harwyn", "Harys", "Hayhead", "Helicent", "Helliweg", "Helman",
            "Hendry", "Henk", "Henly", "Herbert", "Heward", "Hibald", "Hilmar",
            "hllor", "Hobb", "Hobber", "Hod", "Hodor", "Hoke", "Hop", "Horas",
            "Horton", "Hosman", "Hosteen", "Hoster", "Hot", "Hother", "Hotho",
            "Howland", "Hugh", "Hugo", "Hullen", "Humfrey", "Hyle", "Iggo",
            "Igon", "Illifer", "Illyrio", "Ilyn", "Imry", "Ironbelly",
            "Jacelyn", "Jack", "Jacks", "Jaehaerys", "Jafer", "Jaggot",
            "Jaime", "Jammos", "Janos", "Jaqen", "Jared", "Jarl", "Jason",
            "Jasper", "Jate", "Jeffory", "Jeor", "Jeren", "Jhaqo", "Jhogo",
            "Jodge", "Joffrey", "Jojen", "Jommo", "Jon", "Jonnel", "Jonos",
            "Jonothor", "Jorah", "Joramun", "Jorgen", "Jorquen", "Jory",
            "Joseran", "Joseth", "Josmyn", "Joss", "Josua", "Joth", "Joy",
            "Jurne", "Jyck", "Kaeth", "Karl", "Karlon", "Karyl", "Kedge",
            "Kedry", "Kemmett", "Kenned", "Kennos", "Ketter", "Kevan", "Khal",
            "Khorane", "Kirby", "Kirth", "Koss", "Kraznys", "Kromm",
            "Kurleket", "Kurz", "Kyle", "Kym", "Lambert", "Lancel", "Larence",
            "Lark", "Lazy", "Lem", "Lenn", "Lennocks", "Lenwood", "Lenyl",
            "Leo", "Leobald", "Lester", "Lew", "Lewyn", "Lewys", "Leyton",
            "Lharys", "Lister", "Lomas", "Lommy", "Lomys", "Loras", "Lorcas",
            "Lord", "Loren", "Lorent", "Lorimer", "Lormelle", "Lorren",
            "Lothar", "Lothor", "Lucamore", "Lucan", "Lucantine", "Lucas",
            "Luceon", "Lucias", "Lucimore", "Lucion", "Luco", "Lucos", "Luke",
            "Lum", "Luthor", "Luwin", "Lyle", "Lyman", "Lymond", "Lyn", "Lync",
            "Lyonel", "Mace", "Mad", "Maegor", "Maekar", "Maelys", "Mag",
            "Mago", "Mallador", "Malleon", "Mallor", "Malwyn", "Mance",
            "Mandon", "Manfred", "Manfrey", "Manfryd", "Maric", "Marillion",
            "Mark", "Marlon", "Maron", "Marq", "Martyn", "Marwyn", "Maslyn",
            "Mathis", "Matt", "Matthar", "Matthos", "Maynard", "Mebble",
            "Medgar", "Medger", "Medwick", "Meizo", "Melaquin", "Meldred",
            "Mellario", "Melwyn", "Melwys", "Meribald", "Merlon", "Mern",
            "Mero", "Merrell", "Merrett", "Merrit", "Meryn", "Michael",
            "Mikken", "Mohor", "Mollander", "Mollos", "Moon", "Mord",
            "Mordane", "Moreo", "Morgan", "Morgarth", "Morgil", "Moribald",
            "Moro", "Morosh", "Morrec", "Mors", "Mortimer", "Morton", "Moryn",
            "Mudge", "Mullin", "Munda", "Murch", "Murenmure", "Mycah",
            "Mychel", "Myles", "Nage", "Naggle", "Narbert", "Ned", "Nestor",
            "Night", "Noho", "Norbert", "Norjen", "Normund", "Norne", "Norren",
            "Notch", "Nute", "Nymos", "Oberyn", "Ocley", "Ogo", "Old",
            "Ollidor", "Ollo", "Olymer", "Olyvar", "Omer", "Ondrew", "Orbelo",
            "Orbert", "Orell", "Orivel", "Orland", "Ormond", "Oro", "Orton",
            "Orys", "Osbert", "Osmund", "Osmynd", "Osric", "Ossifer", "Ossy",
            "Oswell", "Othell", "Otho", "Othor", "Otter", "Otto", "Ottomore",
            "Ottyn", "Owen", "Parmen", "Patchface", "Pate", "Patrek", "Paxter",
            "Pearse", "Perestan", "Perros", "Perwyn", "Peter", "Petyr",
            "Philip", "Plummer", "Podrick", "Polliver", "Pono", "Porther",
            "Portifer", "Poxy", "Praed", "Prendahl", "Preston", "Puckens",
            "Pudding", "Puddingfoot", "Pycelle", "Pylos", "Pypar", "Qalen",
            "Qarl", "Qarlton", "Qarro", "Qhored", "Qos", "Qotho", "Quaithe",
            "Quaro", "Quellon", "Quent", "Quenten", "Quentin", "Quenton",
            "Quentyn", "Quincy", "Quort", "Qyburn", "Qyle", "Rafe", "Rafford",
            "Ragnor", "Ragwyle", "Rakharo", "Ralf", "Ramsay", "Randyll",
            "Rast", "Rat", "Rattleshirt", "Rawney", "Raymar", "Raymond",
            "Raymun", "Raymund", "Raynald", "Raynard", "Red", "Redtusk",
            "Reek", "Regenard", "Renly", "Reynard", "Reysen", "Rhaegar",
            "Rhaego", "Rhogoro", "Ricasso", "Richard", "Rickard", "Rickon",
            "Rigney", "Rob", "Robar", "Robb", "Robert", "Robett", "Robin",
            "Robyn", "Rodrik", "Rodwell", "Roger", "Roland", "Rolder", "Rolfe",
            "Rollam", "Rolland", "Rolley", "Rolph", "Romny", "Ronald", "Ronel",
            "Ronnel", "Ronnet", "Roone", "Roose", "Rorge", "Roro", "Roryn",
            "Rowena", "Royce", "Rudge", "Rufus", "Runceford", "Runcel",
            "Rupert", "Rus", "Russell", "Ryam", "Rycherd", "Ryger", "Ryk",
            "Ryman", "Rymolf", "Ryon", "Salladhor", "Salloreon", "Sam",
            "Samwell", "Sand", "Sandor", "Sargon", "Satin", "Sawane",
            "Sawwood", "Sebaston", "Sedgekins", "Selmond", "Selwyn", "Serwyn",
            "Shadd", "Shadrich", "Shagga", "Shagwell", "Sherrit", "Sigfry",
            "Sigfryd", "Sigorn", "Sigrin", "Simon", "Skittrick", "Skyte",
            "Sleepy", "Smiling", "Softfoot", "Spotted", "Squint", "Stafford",
            "Stannis", "Steffarion", "Steffon", "Stevron", "Stiv", "Stone",
            "Stonehand", "Stygg", "Styr", "Sumner", "Sylas", "Symon", "Symond",
            "Syrio", "Talbert", "Tallad", "Tanton", "Tarle", "Temmo",
            "Ternesio", "Terrance", "Terrence", "Terro", "Theo", "Theobald",
            "Theodan", "Theodore", "Theomar", "Theomore", "Theon", "Thomax",
            "Thoren", "Thormor", "Thoros", "Three", "Tickler", "Tim", "Timeon",
            "Timett", "Timon", "Timoth", "Tion", "Titus", "Tobbot", "Tobho",
            "Todder", "Todric", "Toefinger", "Tom", "Tomard", "Tommard",
            "Tommen", "TomToo", "Toregg", "Tormund", "Torrek", "Torren",
            "Torrhen", "Torwold", "Torwynd", "Tothmure", "Trebor", "Tregar",
            "Tremond", "Tristan", "Tristifer", "Tristimun", "Triston",
            "Trystane", "Tuffleberry", "Tumberjon", "Turnip", "Turquin",
            "Tybolt", "Tygett", "Tymor", "Tyrek", "Tyrion", "Tytos", "Tywin",
            "Ulf", "Uller", "Ulrick", "Ulwyck", "Umfred", "Urek", "Urras",
            "Urrigon", "Urron", "Urzen", "Utherydes", "Uthor", "Vaellyn",
            "Varamyr", "Vardis", "Vargo", "Varly", "Varys", "Vayon", "Vickon",
            "Victarion", "Victor", "Viserys", "Vortimer", "Vylarr", "Vyman",
            "Walder", "Waldon", "Walgrave", "Wallace", "Wallen", "Walton",
            "Waltyr", "Warren", "Warryn", "Wat", "Watt", "Watty", "Waymar",
            "Wayn", "Weeper", "Weese", "Wendamyr", "Wendel", "Wendell",
            "Werlag", "Wex", "Whalen", "Wilbert", "Will", "Willam", "Willamen",
            "Willas", "Willem", "William", "Willifer", "Willis", "Willit",
            "Willum", "Wolmer", "Wulfe", "Wyl", "Wylis", "Wyman", "Wynton",
            "Ygon", "Yohn", "Yoren", "Yorko", "Yormwell", "Zachery",
            "Zarabelo", "Zollo"],
        "last":["Adarys", "Allyrion", "Ambrose", "Antaryon", "Arryn",
            "Ashford", "Axe", "Baelish", "Ball", "Banefort", "Bar",
            "Baratheon", "Beesbury", "Belmore", "Bettley", "Blackbar",
            "Blackberry", "Blackfyre", "Blackmont", "Blackthumb", "Blacktyde",
            "Blackwood", "Blount", "Boggs", "Boil", "Bolling", "Bolton",
            "Borrell", "Botley", "Boy", "Bracken", "Brax", "Broom",
            "Browntooth", "Brune", "Bulwer", "Bushy", "Butterwell", "Byrch",
            "Bywater", "Cafferen", "Caron", "Cassel", "Caswell", "Celtigar",
            "Cerwyn", "Charlton", "Chelsted", "Chester", "Chyttering",
            "Clegane", "Clifton", "Cockshaw", "Codd", "Coldwater", "Cole",
            "Condon", "Conklyn", "Connington", "cont", "Cook", "Corbray",
            "Costayne", "Cox", "Crabb", "Crakehall", "Crane", "Crowkiller",
            "Cupps", "Cuy", "Dalt", "Darklyn", "Darry", "Dayne", "Deem",
            "Dick", "Dimittis", "Dondarrion", "Drogo", "Drumm", "Dunstable",
            "Dustin", "Egen", "Estermont", "Estren", "Farman", "Farring",
            "Farrow", "Farwynd", "Fell", "Flatnose", "Flint", "Florent",
            "Flowers", "Foote", "Forel", "Fossoway", "Fowler", "Freeborn",
            "Frey", "Gardener", "Gargalen", "Gimpknee", "Glover", "Goodbrook",
            "Goodbrother", "Gower", "Grafton", "Grandison", "Greenfield",
            "Greenhands", "Greenhill", "Grell", "Grey", "Greyiron", "Greyjoy",
            "Grimm", "Grove", "Haigh", "Harclay", "Hardyng", "Harlaw", "Hasty",
            "Heddle", "Hetherspoon", "Hewett", "Hightower", "Hill", "Hoare",
            "Hoat", "Hornwood", "Horpe", "Hotah", "Humble", "Hunt", "Hunter",
            "Huntsman", "II", "III", "Inchfield", "Ironfoot", "IV", "Jack",
            "Jast", "Jordayne", "Karstark", "Kenning", "Kettleblack", "King",
            "Knight", "Lannister", "Leek", "Lefford", "Leo", "Leygood",
            "Liddle", "Locke", "Long", "Longbough", "Longthorpe", "Lonmouth",
            "Lophand", "Lorch", "Lothston", "Lusty", "Lychester", "Lydden",
            "Lynderly", "Mage", "Mahr", "Mallister", "Manderly", "Manwoody",
            "Mar", "Marbrand", "Marsh", "Martell", "Meadows", "Merlyn",
            "Merryweather", "Mertyns", "mo", "Mollen", "Moore", "Mooton",
            "Mopatis", "Moreland", "Mormont", "Morrigen", "Mott", "Mudd",
            "Mullendore", "Myre", "na", "Naharis", "Nayland", "Norcross",
            "Norrey", "Norridge", "Noye", "Oakheart", "Oarsman", "of",
            "Ormollen", "Osgrey", "Otherys", "Paege", "Pate", "Payne", "Peake",
            "Peckledon", "Penny", "Penrose", "Pie", "Pimm", "Piper", "Plumm",
            "Poole", "Potter", "Pox", "Prestayn", "Prester", "Pyke", "Qorgyle",
            "Quaynis", "Quickbow", "Rayder", "Redfort", "Redwyne", "Reed",
            "Reyne", "Rhysling", "Risley", "Rivers", "Roote", "Rowan", "Royce",
            "Ruttiger", "Ryger", "Ryn", "Ryswell", "Saan", "Saltcliffe",
            "Sand", "Santagar", "Sarsfield", "Sathmantes", "Sawyer",
            "Seaworth", "Selmy", "Serry", "Sharp", "Shett", "Sixskins",
            "Slynt", "Smallwood", "Snakes", "Snow", "Sparr", "Sphynx",
            "Spicer", "Stackspear", "Staedmon", "Stark", "Stilwood", "Stone",
            "Stonehouse", "Stonetree", "Stoops", "Storm", "Stout", "Suggs",
            "Sunderland", "Swann", "Swyft", "Tallhart", "Targaryen", "Tarly",
            "Tarth", "Tattersalt", "Tawney", "Templeton", "Tendyris", "Terys",
            "the", "Thorne", "Thumbs", "Tollett", "Torrent", "Toyne", "Trant",
            "Tully", "Tumitis", "Turnberry", "Tym", "Tyrell", "Uffering",
            "Uhoris", "Uller", "Umber", "Underleaf", "Vaith", "Vance",
            "Varner", "Vikary", "Volentin", "Volmark", "Votar", "Votyris",
            "Vypren", "Vyrwel", "Wagstaff", "Walder", "Watch", "Waters",
            "Waxley", "Wayn", "Waynwood", "Weaver", "Webber", "Wells",
            "Westerling", "Whent", "Willum", "Wode", "Woodwright", "Worm",
            "Wull", "Wylde", "Wynch", "Wythers", "XII", "Yarwyck", ""]},}
